pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Clonar el repositorio
                git 'https://github.com/PamTommasini/hola-mundo-cicd.git'
            }
        }
        stage('Install') {
            steps {
                // Instalar dependencias localmente (opcional, útil para testear sin Docker)
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Test') {
            steps {
                // Ejecutar tests
                sh 'python -m unittest discover tests'
            }
        }
        stage('Build Docker Image') {
            steps {
                // Construir la imagen Docker
                sh 'docker build -t hello-world-python .'
            }
        }
        stage('Run Docker Container') {
            steps {
                // Ejecutar la imagen en un contenedor
                sh 'docker run --rm hello-world-python'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completada.'
        }
        success {
            echo 'Éxito: Todas las etapas completadas.'
        }
        failure {
            echo 'Fallo: Revisa la configuración o los logs.'
        }
    }
}
