pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Clonar el repositorio
                git 'https://github.com/usuario/hello-world-python.git'
            }
        }
        stage('Build Docker Images') {
            steps {
                // Construir los contenedores con docker-compose
                sh 'docker-compose build'
            }
        }
        stage('Run Services') {
            steps {
                // Levantar servicios
                sh 'docker-compose up -d'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completada.'
        }
        success {
            echo 'Éxito: Aplicación desplegada con NGINX.'
        }
        failure {
            echo 'Fallo: Revisa la configuración o los logs.'
        }
    }
}
